MachineGuts_Django/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('shop.urls')),
]

shop/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout
from . import views

app_name = 'shop'

urlpatterns = [
    # 127.0.0.1:8000/
    url(r'^$', views.index, name='index'),

    # 127.0.0.1:8000/register/
    url(r'^register/$', views.register, name='register'),

    # 127.0.0.1:8000/store/
    url(r'^store/$', views.store, name='store'),

    # 127.0.0.1:8000/cart/
    url(r'^cart/$', views.cart, name='cart'),

    # 127.0.0.1:8000/deals/
    url(r'^deals/$', views.deals, name='deals'),

    # 127.0.0.1:8000/login/
    url(r'^login/$', views.login_user, name='login_user'),

    # 127.0.0.1:8000/logout/
    url(r'^logout/$', views.logout_user, name='logout_user')
]

shop/models.py
from django.db import models


# Create your models here.
class Item(models.Model):
    name = models.CharField(max_length=250)
    manufacturer = models.CharField(max_length=250)
    price = models.FloatField()
    img_url = models.CharField(max_length=500)
    sale = models.BooleanField(default=False)

    def __str__(self):
        return self.name + ' - ' + self.manufacturer

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from .models import Item


# Create your views here.
def index(request):
    return render(request, 'shop/index.html')


def register(request):
    if request.method == "POST":
        username = request.POST['username']
        email = request.POST['email']
        email_confirm = request.POST['email_confirm']
        password = request.POST['password']
        password_confirm = request.POST['password_confirm']

        errors = validate(username, email, email_confirm, password, password_confirm)
        if errors is None:
            user = User.objects.create_user(username, email, password)
            user.save()
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('shop:index')
        else:
            # used to refill registration form with previously inputted data
            data = {'username': username, 'email': email, 'email_confirm': email_confirm}
            return render(request, 'shop/register.html', {'errors': errors, 'data': data})

    return render(request, 'shop/register.html')


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('shop:index')
        else:
            context = {'error_message': 'Username or password are incorrect', 'username': username}
            return render(request, 'shop/index.html', context)

    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


def logout_user(request):
    logout(request)
    return redirect('shop:index')


def validate(username, email, email_confirm, password, password_confirm):

    errors = {'username_error': None,
              'email_error': None,
              'email_confirm_error': None,
              'password_error': None,
              'password_confirm_error': None}

    if not username:
        errors['username_error'] = 'Username field cannot be blank.'

    if not email:
        errors['email_error'] = 'Email field cannot be blank.'

    if not email_confirm:
        errors['email_confirm_error'] = 'Confirm email field cannot be blank.'

    if email != email_confirm:
        errors['email_confirm_error'] = 'Email and confirm email fields do not match.'

    if not password:
        errors['password_error'] = 'Password field cannot be blank.'

    if not password_confirm:
        errors['password_confirm_error'] = 'Confirm password field cannot be blank.'

    if password != password_confirm:
        errors['password_confirm_error'] = 'Password and confirm password fields do not match.'

    for key, value in errors.items():
        if value is None:
            continue
        else:
            return errors

    return None


def store(request):
    items = Item.objects.all()
    return render(request, 'shop/store.html', {'items': items})


def cart(request):
    items = Item.objects.filter(sale=True)
    return render(request, 'shop/cart.html', {'items': items})

def deals(request):
    items = Item.objects.filter(sale=True)
    return render(request, 'shop/deals.html', {'items': items})

shop/templates/shop/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Machine Guts - Home{% endblock %}</title>
    <meta charset="utf-8">
    {% load staticfiles %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- This style is always needed so its placed here in base -->
    <link rel="stylesheet" type="text/css" href="{% static 'shop/login_modal.css' %}">
  <!--  personal css-->
    {% block css_links %}

    {% endblock %}
<!--
green:#27ae60
dark blue: #2c3e50
white: #bdc3c7
-->

</head>
<body>
    <!--navigation bar-->
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'shop:index' %}">Home</a></li>
                    <li ><a href="{% url 'shop:store' %}">Products</a></li>
                    <li><a href="{% url 'shop:deals' %}">Deals</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#">
                        <span class="glyphicon glyphicon-user"></span>
                        {% if user.is_authenticated %}
                            Hello {{ user.username }}!
                        {% else %}
                            Hello Guest!
                        {% endif %}
                    </a></li>
                    <li>
                        {% if user.is_authenticated %}
                            <a href="{% url 'shop:logout_user' %}"><span class="glyphicon glyphicon-user"></span> Logout</a>
                        {% else %}
                            <a href="#" data-toggle="modal" data-target="#login-modal">
                            <span class="glyphicon glyphicon-user"></span> Login</a>
                        {% endif %}
                    </li>
                    <li><a href="{% url 'shop:cart' %}"><span class="glyphicon glyphicon-shopping-cart"></span> Cart</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Login Modal -->
    <div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
        <div class="modal-dialog">
            <div class="loginmodal-container">
                <h1 id="loginheader">Login to Your Account</h1><br>
                <form class="form-horizontal" role="form" action="{% url 'shop:login_user' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% if error_message %}

                        <span class="text-danger small">{{ error_message }}</span>

                    {% endif %}
                    <input type="text" name="username" placeholder="Username" value="{{ username }}">
                    <input type="password" name="password" placeholder="Password">
                    <input type="submit" class="login loginmodal-submit" value="Login">
                </form>

                <div class="login-help">
                    <a href="{% url 'shop:register' %}">Register</a> - <a href="#">Forgot Password?</a>
                </div>
            </div>
        </div>
      </div>

    {% block body %}    {% comment %}Rest of body from other layouts go here{% endcomment %}
    {% endblock %}
</body>
</html>

shop/templates/shop/cart.html
{% extends 'shop/base.html' %}
{% load staticfiles %}
{% block title %}Store{% endblock %}
{% block css_links %}
    <link rel="stylesheet" type="text/css" href="{% static 'shop/cart.css' %}">
{% endblock %}

{% block body %}
    <div class="container holder">

        <div class="container cart">
            {% for item in items %}
                <div class="row row-cart">
                    <div class="col-sm-2">
                        <div class="card">
                            <img class="card-img-top" src="{{ item.img_url }}">
                        </div>
                    </div>
                    <div class="col-sm-4 va">{{ item.name }}</div>
                    <div class="col-sm-1 va"> ${{ item.price }}</div>
                    <div class="col-sm-2 va">Free Delivery</div>
                    <div class="col-sm-1 va">${{ item.price|add:"-15" }}</div>
                    <div class="col-sm-2 va">
                        <button class="btn btn-danger btn-block">Remove</button>
                    </div>
                </div>
            {% endfor %}

{#            <div class="row row-cart">#}
{#                <div class="col-sm-2">#}
{#                    <div class="card">#}
{#                        <img class="card-img-top" src="http://s3.amazonaws.com/etntmedia/media/images/ext/842849976/greasy-fast-food.jpg">#}
{#                    </div>#}
{#                </div>#}
{#                <div class="col-sm-4 va">Asus MSSDF29993 17 inch</div>#}
{#                <div class="col-sm-1 va"> $100.99</div>#}
{#                <div class="col-sm-2 va">Free Delivery</div>#}
{#                <div class="col-sm-1 va">Sub Total</div>#}
{#                <div class="col-sm-2 va">#}
{#                    <button class="btn btn-danger btn-block">Remove</button>#}
{#                </div>#}
{#            </div>#}
{##}
{#            <div class="row row-cart">#}
{#                <div class="col-sm-2">#}
{#                    <div class="card">#}
{#                        <img class="card-img-top" src="http://s3.amazonaws.com/etntmedia/media/images/ext/842849976/greasy-fast-food.jpg">#}
{#                    </div>#}
{#                </div>#}
{#                <div class="col-sm-4 va">Asus MSSDF29993 17 inch</div>#}
{#                <div class="col-sm-1 va"> $100.99</div>#}
{#                <div class="col-sm-2 va">Free Delivery</div>#}
{#                <div class="col-sm-1 va">Sub Total</div>#}
{#                <div class="col-sm-2 va">#}
{#                    <button class="btn btn-danger btn-block">Remove</button>#}
{#                </div>#}
{#            </div>#}
{##}
{#            <div class="row row-cart">#}
{#                <div class="col-sm-2">#}
{#                    <div class="card">#}
{#                        <img class="card-img-top" src="http://s3.amazonaws.com/etntmedia/media/images/ext/842849976/greasy-fast-food.jpg">#}
{#                    </div>#}
{#                </div>#}
{#                <div class="col-sm-4 va">Asus MSSDF29993 17 inch</div>#}
{#                <div class="col-sm-1 va"> $100.99</div>#}
{#                <div class="col-sm-2 va">Free Delivery</div>#}
{#                <div class="col-sm-1 va">Sub Total</div>#}
{#                <div class="col-sm-2 va">#}
{#                    <button class="btn btn-danger btn-block">Remove</button>#}
{#                </div>#}
{#            </div>#}
{##}
{#            <div class="row row-cart">#}
{#                <div class="col-sm-2">#}
{#                    <div class="card">#}
{#                        <img class="card-img-top" src="http://s3.amazonaws.com/etntmedia/media/images/ext/842849976/greasy-fast-food.jpg">#}
{#                    </div>#}
{#                </div>#}
{#                <div class="col-sm-4 va">Asus MSSDF29993 17 inch</div>#}
{#                <div class="col-sm-1 va"> $100.99</div>#}
{#                <div class="col-sm-2 va">Free Delivery</div>#}
{#                <div class="col-sm-1 va">Sub Total</div>#}
{#                <div class="col-sm-2 va">#}
{#                    <button class="btn btn-danger btn-block">Remove</button>#}
{#                </div>#}
{#            </div>#}
{##}
{#            <div class="row row-cart">#}
{#                <div class="col-sm-2">#}
{#                    <div class="card">#}
{#                        <img class="card-img-top" src="http://s3.amazonaws.com/etntmedia/media/images/ext/842849976/greasy-fast-food.jpg">#}
{#                    </div>#}
{#                </div>#}
{#                <div class="col-sm-4 va">Asus MSSDF29993 17 inch</div>#}
{#                <div class="col-sm-1 va"> $100.99</div>#}
{#                <div class="col-sm-2 va">Free Delivery</div>#}
{#                <div class="col-sm-1 va">Sub Total</div>#}
{#                <div class="col-sm-2 va">#}
{#                    <button class="btn btn-danger btn-block">Remove</button>#}
{#                </div>#}
{#            </div>#}
{##}
{#            <div class="row row-cart">#}
{#                <div class="col-sm-2">#}
{#                    <div class="card">#}
{#                        <img class="card-img-top" src="http://s3.amazonaws.com/etntmedia/media/images/ext/842849976/greasy-fast-food.jpg">#}
{#                    </div>#}
{#                </div>#}
{#                <div class="col-sm-4 va">Asus MSSDF29993 17 inch</div>#}
{#                <div class="col-sm-1 va"> $100.99</div>#}
{#                <div class="col-sm-2 va">Free Delivery</div>#}
{#                <div class="col-sm-1 va">Sub Total</div>#}
{#                <div class="col-sm-2 va">#}
{#                    <button class="btn btn-danger btn-block">Remove</button>#}
{#                </div>#}
{#            </div>#}
{##}
{#            <div class="row row-cart">#}
{#                <div class="col-sm-2">#}
{#                    <div class="card">#}
{#                        <img class="card-img-top" src="http://s3.amazonaws.com/etntmedia/media/images/ext/842849976/greasy-fast-food.jpg">#}
{#                    </div>#}
{#                </div>#}
{#                <div class="col-sm-4 va">Asus MSSDF29993 17 inch</div>#}
{#                <div class="col-sm-1 va"> $100.99</div>#}
{#                <div class="col-sm-2 va">Free Delivery</div>#}
{#                <div class="col-sm-1 va">Sub Total</div>#}
{#                <div class="col-sm-2 va">#}
{#                    <button class="btn btn-danger btn-block">Remove</button>#}
{#                </div>#}
{#            </div>#}
{##}
{#            <div class="row row-cart">#}
{#                <div class="col-sm-2">#}
{#                    <div class="card">#}
{#                        <img class="card-img-top" src="http://s3.amazonaws.com/etntmedia/media/images/ext/842849976/greasy-fast-food.jpg">#}
{#                    </div>#}
{#                </div>#}
{#                <div class="col-sm-4 va">Asus MSSDF29993 17 inch</div>#}
{#                <div class="col-sm-1 va"> $100.99</div>#}
{#                <div class="col-sm-2 va">Free Delivery</div>#}
{#                <div class="col-sm-1 va">Sub Total</div>#}
{#                <div class="col-sm-2 va">#}
{#                    <button class="btn btn-danger btn-block">Remove</button>#}
{#                </div>#}
{#            </div>#}
        </div>

        <div class="button-wrapper">
            <div class="col-sm-4"></div>
            <div class="col-sm-4 ">
                <button class="btn btn-success btn-block btn-lg">Buy</button>
            </div>
            <div class="col-sm-4"></div>
        </div>


    </div>


    <footer class="container-fluid text-center footer">
        <p>Online Store Copyright</p>
        <div class="container">
            <div class="row greeting">
                <div class="col-sm-3">
                    <ul>
                        <li class="heading">Get to Know Us</li>
                        <li>Careers</li>
                        <li>About Machine Guts</li>
                        <li>Investor Relations</li>
                        <li>Machine Guts Devices</li>
                    </ul>
                </div>
                <div class="col-sm-3">
                    <ul>
                        <li class="heading">Make Money with Us</li>
                        <li> Sell on Machine Guts</li>
                        <li>Sell your Services on Machine Guts</li>
                        <li>Sell your apps on Machine Guts</li>
                        <li>Become an Affiliate</li>
                        <li>Advertise  your produts</li>
                        <li>Self-publish with Us</li>
                        <li>Become an Machine Guts Vendor</li>
                    </ul>
                </div>
                <div class="col-sm-3">
                    <ul>
                        <li class="heading">Machine Guts Products</li>
                        <li>Machineguts.com Rewards Visa Card</li>
                        <li>Machineguts.com Store Card</li>
                        <li>Machineguts.com Corporate Credit Line</li>
                        <li>Shop with Points</li>
                        <li>Shop with Points</li>
                        <li>Credit Card Marketplace</li>
                        <li>Reload Your Balance</li>
                    </ul>
                </div>
                <div class="col-sm-3">

                    <ul>
                        <li class="heading">Let Us Help You</li>
                        <li>Your Account</li>
                        <li>Your Orders</li>
                        <li>Shipping Rates and Policies</li>
                        <li>Amazon Prime</li>
                        <li>Returns and Replacements</li>
                        <li>Manage Your Content and Devices</li>
                        <li>Machine Guts Assistant</li>
                        <li>Help</li>
                    </ul>

                </div>
            </div>
        </div>
    </footer>
{% endblock %}

shop/templates/shop/deals.html
{% extends 'shop/base.html' %}
{% load staticfiles %}
{% block title %}Deals{% endblock %}
{% block css_links %}
    <link rel="stylesheet" type="text/css" href="{% static 'shop/deals.css' %}">
{% endblock %}

{% block body %}



    <div class="scroll">

    <div class="container">
      <div class="jumbotron">
        <h1>Monster Holiday Deals!</h1>
        <p> Save big this holiday season by using signing up for Machine Guts Rewards Plan! </p>
      </div>
    </div>


        <div class="container items">
         <div class="container">
            {% for item in items %}
                <div class="col-sm-4 col-lg-3 ">
                    <div class="panel panel-success">
                        <div class="panel-heading">Sale!</div>
                        <div class="panel-body"><img src="{{ item.img_url }}" class="img-responsive" style="width:200px; height:200px;" alt="Image"></div>
                        <div class="panel-footer">Name: {{ item.name }}</div>
                        <div class="panel-footer">Manufacturer: {{ item.manufacturer }}</div>
                        <div class="panel-footer">Price: ${{ item.price|add:'-15' }}</div>
                        <div class="panel-footer"><button class="btn btn-success btn-lg btn-block">Purchase</button></div>
                    </div>
                </div>
            {% endfor %}


            </div>
        </div>
    </div>


    <footer class="container-fluid text-center footer">
        <p>Online Store Copyright</p>
        <div class="container">
            <div class="row greeting">
                <div class="col-sm-3">
                    <ul>
                        <li class="heading">Get to Know Us</li>
                        <li>Careers</li>
                        <li>About Machine Guts</li>
                        <li>Investor Relations</li>
                        <li>Machine Guts Devices</li>
                    </ul>
                </div>
                <div class="col-sm-3">
                 <ul>
                     <li class="heading">Make Money with Us</li>
                     <li> Sell on Machine Guts</li>
                     <li>Sell your Services on Machine Guts</li>
                     <li>Sell your apps on Machine Guts</li>
                     <li>Become an Affiliate</li>
                     <li>Advertise  your produts</li>
                     <li>Self-publish with Us</li>
                     <li>Become an Machine Guts Vendor</li>
                 </ul>
                </div>
                <div class="col-sm-3">
                    <ul>
                        <li class="heading">Machine Guts Products</li>
                        <li>Machineguts.com Rewards Visa Card</li>
                        <li>Machineguts.com Store Card</li>
                        <li>Machineguts.com Corporate Credit Line</li>
                        <li>Shop with Points</li>
                        <li>Shop with Points</li>
                        <li>Credit Card Marketplace</li>
                        <li>Reload Your Balance</li>
                    </ul>
               </div>
                <div class="col-sm-3">

                 <ul>
                     <li class="heading">Let Us Help You</li>
                     <li>Your Account</li>
                     <li>Your Orders</li>
                     <li>Shipping Rates and Policies</li>
                     <li>Amazon Prime</li>
                     <li>Returns and Replacements</li>
                     <li>Manage Your Content and Devices</li>
                     <li>Machine Guts Assistant</li>
                     <li>Help</li>
                 </ul>

                </div>
            </div>
        </div>
    </footer>
{% endblock %}

shop/templates/shop/index.html
{% extends 'shop/base.html' %}
{% load staticfiles %}
{% block css_links %}
    <link rel="stylesheet" type="text/css" href="{% static 'shop/index.css' %}">
{% endblock %}

{% block body %}
<!--header-->
<div class="jumbotron">
  <p id="site-title">{ Machine Guts } </p>
  <h4>Your first and last stop for all your computer needs</h4>
</div>

{#    carousel #}

    <div id="slidingtext">
        <h2 id="carouseltitle">What our customers say</h2>
        <div id="myCarousel" class="carousel slide text-center" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
          </ol>

          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox">
            <div class="item active">
            <h4>"This company is the best. Way better than Amazon.com and the Devs are cute too!"<br><span style="font-style:normal;"> Elrich Bachman, Majority Investor, Pied Piper</span></h4>
            </div>
            <div class="item">
              <h4>"Their back end code is not total crap..."<br><span style="font-style:normal;">Bertman Gilfoyle, Senior Systems Analyst, Pied Piper</span></h4>
            </div>
            <div class="item">
              <h4>"Does this gold chain make me look douchey?!"<br><span style="font-style:normal;">Dinesh Chugtai, Senior Programmer, Pied Piper</span></h4>
            </div>
          </div>

          <!-- Left and right controls -->
          <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
    </div>


    <!-- Set height and width with CSS -->
<div id="googleMap" style="height:400px;width:100%;"></div>

<!-- Add Google Maps -->
<script src="http://maps.googleapis.com/maps/api/js"></script>
<script>
var myCenter = new google.maps.LatLng(26.306042, -98.174801);

function initialize() {
var mapProp = {
center:myCenter,
zoom:12,
scrollwheel:false,
draggable:false,
mapTypeId:google.maps.MapTypeId.ROADMAP
};

var map = new google.maps.Map(document.getElementById("googleMap"),mapProp);

var marker = new google.maps.Marker({
position:myCenter,
});

marker.setMap(map);
}

google.maps.event.addDomListener(window, 'load', initialize);
</script>

<footer class="container-fluid text-center footer">
  <p>Online Store Copyright</p>  
  <div class="container">
    <div class="row greeting">
        <div class="col-sm-3">          
            <ul>
                <li class="heading">Get to Know Us</li>
                <li>Careers</li>
                <li>About Machine Guts</li>
                <li>Investor Relations</li>
                <li>Machine Guts Devices</li>
            </ul>
        </div>
        <div class="col-sm-3">
         <ul>
             <li class="heading">Make Money with Us</li>
             <li> Sell on Machine Guts</li>
             <li>Sell your Services on Machine Guts</li>
             <li>Sell your apps on Machine Guts</li>
             <li>Become an Affiliate</li>
             <li>Advertise  your produts</li>
             <li>Self-publish with Us</li>
             <li>Become an Machine Guts Vendor</li>
         </ul>
        </div>
        <div class="col-sm-3">
            <ul>
                <li class="heading">Machine Guts Products</li>
                <li>Machineguts.com Rewards Visa Card</li>
                <li>Machineguts.com Store Card</li>
                <li>Machineguts.com Corporate Credit Line</li>
                <li>Shop with Points</li>
                <li>Shop with Points</li>
                <li>Credit Card Marketplace</li>
                <li>Reload Your Balance</li>
            </ul>
       </div>
        <div class="col-sm-3">
         
         <ul>
             <li class="heading">Let Us Help You</li>
             <li>Your Account</li>
             <li>Your Orders</li>
             <li>Shipping Rates and Policies</li>
             <li>Amazon Prime</li>
             <li>Returns and Replacements</li>
             <li>Manage Your Content and Devices</li>
             <li>Machine Guts Assistant</li>
             <li>Help</li>
         </ul>

        </div>
    </div>
    </div>
</footer>

{% endblock %}

shop/templates/shop/register.html
{% extends 'shop/base.html' %}
{% load staticfiles %}
{% block title %}Register{% endblock %}
{% block css_links %}
    <link rel="stylesheet" type="text/css" href="{% static 'shop/register.css' %}">
{% endblock %}

{% block body %}
    <div class="container contain">
        <div id="title">Register Here</div>
        <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% comment %}<p>{{ errors.fuckthis }} </p>{% endcomment %}
            <div class="form-group">
                {% if errors.username_error %}
                    <div class="col-sm-offset-2 col-sm-10">
                    <span class="text-danger small">{{ errors.username_error }}</span>
                    </div>
                {% endif %}
                <label for="pwd">Username:</label>
                <input type="text" class="form-control" id="username" name="username" value="{{ data.username }}">
            </div>
            <div class="form-group">
                {% if errors.email_error %}
                    <div class="col-sm-offset-2 col-sm-10">
                    <span class="text-danger small">{{ errors.email_error }}</span>
                    </div>
                {% endif %}
                <label for="email">Email address:</label>
                <input type="email" class="form-control" id="email" name="email" value="{{ data.email }}">
            </div>

            <div class="form-group">
                {% if errors.email_confirm_error %}
                    <div class="col-sm-offset-2 col-sm-10">
                    <span class="text-danger small">{{ errors.email_confirm_error }}</span>
                    </div>
                {% endif %}
                <label for="email">Confirm Email address:</label>
                <input type="email" class="form-control" id="email" name="email_confirm" value="{{ data.email_confirm }}">
            </div>
            <div class="form-group">
                {% if errors.password_error %}
                    <div class="col-sm-offset-2 col-sm-10">
                    <span class="text-danger small">{{ errors.password_error }}</span>
                    </div>
                {% endif %}
                <label for="pwd">Password:</label>
                <input type="password" class="form-control" id="pwd" name="password">
            </div>
            <div class="form-group">
                {% if errors.password_confirm_error %}
                    <div class="col-sm-offset-2 col-sm-10">
                    <span class="text-danger small">{{ errors.password_confirm_error }}</span>
                    </div>
                {% endif %}
                <label for="pwd">Confirm Password:</label>
                <input type="password" class="form-control" id="pwd" name="password_confirm">
            </div>
            <div class="button-wrapper">
                <button type="submit" class="btn btn-success btn-lg btn-block">Register</button>
            </div>
        </form>
    </div>

{% endblock %}